### ISSUE TITLE
Clarify licenses

### ISSUE THREAD

**Issue by pombredanne** [privazio/alpine_release_info#2]
Your setup.py has these:
```
    license='GPLv3',
```
and this:
```
        'License :: OSI Approved :: MIT License',
```
and the GPL txt in LICENSE...
Which one applies ? do you mind to clarify this?
Thanks!

**Comment by rvalle** [comment]
@pombredanne honestly I did not pay attention to the License.

Lets see, a quick look into Alpine Linux brings this:

https://wiki.alpinelinux.org/wiki/Python_package_policies

Where they propose a MIT license in the template of their python packages. 

Seems reasonable that we pick MIT.

**Comment by rvalle** [comment]
@pombredanne please, reopen the issue if you believe we should pick a different one. Thanks for pointing this out.

**Comment by pombredanne** [comment]
@rvalle any license is good: my only issue was with the ambiguity! thank you for the quick reply.
